=== liquibase/liquibase4/liquibase-common/src/main/resources/liquibase/parser/core/xml/changelog-4.0.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.liquibase.org/xml/ns/changelog"
            xmlns="http://www.liquibase.org/xml/ns/changelog"
            elementFormDefault="qualified">

    <xsd:element name="changeLog">
        <xsd:complexType>
            <xsd:sequence minOccurs="0" maxOccurs="unbounded">
                <xsd:choice>
                    <xsd:element name="changeSet" minOccurs="0" maxOccurs="unbounded">
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:group ref="changeSetChildren" minOccurs="0" maxOccurs="unbounded"/>
                            </xsd:sequence>
                            <xsd:attribute name="id" type="xsd:string" use="required"/>
                            <xsd:attribute name="author" type="xsd:string" use="required"/>
                            <xsd:attribute name="contexts" type="xsd:string"/>
                            <xsd:attribute name="labels" type="xsd:string"/>
                            <xsd:attribute name="dbms" type="xsd:string"/>
                        </xsd:complexType>
                    </xsd:element>
                </xsd:choice>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:group name="changeSetChildren">
        <xsd:sequence>
            <xsd:choice>
                <xsd:element name="query">
                    <xsd:complexType mixed="true">
                        <xsd:attribute name="dbms" type="xsd:string"/>
                        <xsd:attribute name="endDelimiter" type="xsd:string"/>
                        <xsd:attribute name="splitStatements" type="xsd:string"/>
                        <xsd:attribute name="stripComments" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="updateSql">
                    <xsd:complexType mixed="true">
                        <xsd:attribute name="dbms" type="xsd:string"/>
                        <xsd:attribute name="endDelimiter" type="xsd:string"/>
                        <xsd:attribute name="splitStatements" type="xsd:string"/>
                        <xsd:attribute name="stripComments" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="sql">
                    <xsd:complexType mixed="true">
                        <xsd:attribute name="dbms" type="xsd:string"/>
                        <xsd:attribute name="endDelimiter" type="xsd:string"/>
                        <xsd:attribute name="splitStatements" type="xsd:string"/>
                        <xsd:attribute name="stripComments" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="addAutoIncrement">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="autoIncrementDetails" minOccurs="0" maxOccurs="1">
                                <xsd:complexType>
                                    <xsd:attribute name="incrementBy" type="xsd:integer"/>
                                    <xsd:attribute name="startWith" type="xsd:integer"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="columnName" type="xsd:string" use="required"/>
                        <xsd:attribute name="tableName" type="xsd:string"/>
                        <xsd:attribute name="schemaName" type="xsd:string"/>
                        <xsd:attribute name="catalogName" type="xsd:string"/>
                        <xsd:attribute name="dataType" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="addColumns">
                    <xsd:complexType>
                        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
                            <xsd:choice>
                                <xsd:element name="checkConstraint" minOccurs="0" maxOccurs="unbounded">
                                    <xsd:complexType mixed="true">
                                        <xsd:attribute name="disabled" type="xsd:boolean"/>
                                        <xsd:attribute name="name" type="xsd:string"/>
                                        <xsd:attribute name="remarks" type="xsd:string"/>
                                    </xsd:complexType>
                                </xsd:element>
                                <xsd:element name="column" minOccurs="1" maxOccurs="unbounded">
                                    <xsd:complexType>
                                        <xsd:sequence>
                                            <xsd:element name="autoIncrementDetails" minOccurs="0" maxOccurs="1">
                                                <xsd:complexType>
                                                    <xsd:attribute name="incrementBy" type="xsd:integer"/>
                                                    <xsd:attribute name="startWith" type="xsd:integer"/>
                                                </xsd:complexType>
                                            </xsd:element>
                                        </xsd:sequence>
                                        <xsd:attribute name="defaultValue" type="xsd:string"/>
                                        <xsd:attribute name="name" type="xsd:string" use="required"/>
                                        <xsd:attribute name="nullable" type="xsd:boolean"/>
                                        <xsd:attribute name="remarks" type="xsd:string"/>
                                        <xsd:attribute name="type" type="xsd:string"/>
                                        <xsd:attribute name="virtual" type="xsd:boolean"/>
                                    </xsd:complexType>
                                </xsd:element>
                                <xsd:element name="foreignKey" minOccurs="0" maxOccurs="unbounded">
                                    <xsd:complexType>
                                        <xsd:sequence>
                                            <xsd:element name="constraint" minOccurs="1" maxOccurs="unbounded">
                                                <xsd:complexType>
                                                    <xsd:attribute name="baseColumn" type="xsd:string"/>
                                                    <xsd:attribute name="referencedColumn" type="xsd:string"/>
                                                </xsd:complexType>
                                            </xsd:element>
                                        </xsd:sequence>
                                        <xsd:attribute name="deferrable" type="xsd:boolean"/>
                                        <xsd:attribute name="deleteRule" type="xsd:string"/>
                                        <xsd:attribute name="initiallyDeferred" type="xsd:boolean"/>
                                        <xsd:attribute name="name" type="xsd:string"/>
                                        <xsd:attribute name="remarks" type="xsd:string"/>
                                        <xsd:attribute name="updateRule" type="xsd:string"/>
                                        <xsd:attribute name="referencedTableName" type="xsd:string"/>
                                        <xsd:attribute name="referencedTableSchemaName" type="xsd:string"/>
                                        <xsd:attribute name="referencedTableCatalogName" type="xsd:string"/>
                                    </xsd:complexType>
                                </xsd:element>
                                <xsd:element name="primaryKey" minOccurs="0" maxOccurs="unbounded">
                                    <xsd:complexType>
                                        <xsd:sequence>
                                            <xsd:element name="column" minOccurs="1" maxOccurs="unbounded">
                                                <xsd:complexType>
                                                    <xsd:attribute name="name" type="xsd:string"/>
                                                    <xsd:attribute name="direction" type="xsd:string"/>
                                                </xsd:complexType>
                                            </xsd:element>
                                        </xsd:sequence>
                                        <xsd:attribute name="clustered" type="xsd:boolean"/>
                                        <xsd:attribute name="name" type="xsd:string"/>
                                        <xsd:attribute name="remarks" type="xsd:string"/>
                                        <xsd:attribute name="tablespace" type="xsd:string"/>
                                    </xsd:complexType>
                                </xsd:element>
                                <xsd:element name="uniqueConstraint" minOccurs="0" maxOccurs="unbounded">
                                    <xsd:complexType>
                                        <xsd:sequence>
                                            <xsd:element name="column" minOccurs="1" maxOccurs="unbounded"/>
                                        </xsd:sequence>
                                        <xsd:attribute name="deferrable" type="xsd:boolean"/>
                                        <xsd:attribute name="disabled" type="xsd:boolean"/>
                                        <xsd:attribute name="initiallyDeferred" type="xsd:boolean"/>
                                        <xsd:attribute name="name" type="xsd:string"/>
                                        <xsd:attribute name="remarks" type="xsd:string"/>
                                        <xsd:attribute name="tablespace" type="xsd:string"/>
                                        <xsd:attribute name="backingIndexName" type="xsd:string"/>
                                        <xsd:attribute name="backingIndexTableName" type="xsd:string"/>
                                        <xsd:attribute name="backingIndexSchemaName" type="xsd:string"/>
                                        <xsd:attribute name="backingIndexCatalogName" type="xsd:string"/>
                                    </xsd:complexType>
                                </xsd:element>
                            </xsd:choice>
                        </xsd:sequence>
                        <xsd:attribute name="tableName" type="xsd:string"/>
                        <xsd:attribute name="schemaName" type="xsd:string"/>
                        <xsd:attribute name="catalogName" type="xsd:string"/>
                        <xsd:attribute name="dataType" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="addForeignKeys">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="foreignKey" minOccurs="1" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="constraint" minOccurs="1" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:attribute name="baseColumn" type="xsd:string"/>
                                                <xsd:attribute name="referencedColumn" type="xsd:string"/>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                    <xsd:attribute name="deferrable" type="xsd:boolean"/>
                                    <xsd:attribute name="deleteRule" type="xsd:string"/>
                                    <xsd:attribute name="initiallyDeferred" type="xsd:boolean"/>
                                    <xsd:attribute name="name" type="xsd:string"/>
                                    <xsd:attribute name="remarks" type="xsd:string"/>
                                    <xsd:attribute name="updateRule" type="xsd:string"/>
                                    <xsd:attribute name="tableName" type="xsd:string"/>
                                    <xsd:attribute name="schemaName" type="xsd:string"/>
                                    <xsd:attribute name="catalogName" type="xsd:string"/>
                                    <xsd:attribute name="referencedTableName" type="xsd:string"/>
                                    <xsd:attribute name="referencedTableSchemaName" type="xsd:string"/>
                                    <xsd:attribute name="referencedTableCatalogName" type="xsd:string"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="createTable">
                    <xsd:complexType>
                        <xsd:choice maxOccurs="unbounded">
                            <xsd:element name="column" minOccurs="1">
                                <xsd:complexType>
                                    <xsd:attribute name="name" type="xsd:string" use="required"/>
                                    <xsd:attribute name="type" type="xsd:string" use="required"/>
                                    <xsd:attribute name="nullable" type="xsd:boolean"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:choice>
                        <xsd:attribute name="tableName" type="xsd:string" use="required"/>
                        <xsd:attribute name="schemaName" type="xsd:string"/>
                        <xsd:attribute name="catalogName" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="insertData">
                    <xsd:complexType>
                        <xsd:choice maxOccurs="unbounded">
                            <xsd:element name="row" minOccurs="1">
                                <xsd:complexType>
                                    <xsd:choice maxOccurs="unbounded">
                                        <xsd:element name="column" minOccurs="1">
                                            <xsd:complexType>
                                                <xsd:attribute name="name" type="xsd:string" use="required"/>
                                                <xsd:attribute name="value" type="xsd:string" use="required"/>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:choice>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:choice>
                        <xsd:attribute name="tableName" type="xsd:string"/>
                        <xsd:attribute name="schemaName" type="xsd:string"/>
                        <xsd:attribute name="catalogName" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:choice>
        </xsd:sequence>
    </xsd:group>
</xsd:schema>

=== liquibase/liquibase4/liquibase-common/src/test/resources/liquibase/parser/expected/ParserFactoryTest.unparsed.addForeignKeys.xml
<?xml version="1.1" encoding="utf-8"?>
<changeLog xmlns="http://www.liquibase.org/xml/ns/changelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/changelog http://www.liquibase.org/xml/ns/changelog/changelog-4.0.xsd">
    <changeSet author="test" id="1">
        <addForeignKeys>
            <foreignKey deferrable="true" deleteRule="cascade" initiallyDeferred="true" name="abc" remarks="abc" updateRule="cascade" referencedTableName="object_name" referencedTableSchemaName="schema_name" referencedTableCatalogName="cat_name" tableName="object_name" schemaName="schema_name" catalogName="cat_name">
                <constraint baseColumn="abc" referencedColumn="abc"/>
                <constraint baseColumn="abc" referencedColumn="abc"/>
            </foreignKey>
            <foreignKey deferrable="true" deleteRule="cascade" initiallyDeferred="true" name="abc" remarks="abc" updateRule="cascade" referencedTableName="object_name" referencedTableSchemaName="schema_name" referencedTableCatalogName="cat_name" tableName="object_name" schemaName="schema_name" catalogName="cat_name">
                <constraint baseColumn="abc" referencedColumn="abc"/>
                <constraint baseColumn="abc" referencedColumn="abc"/>
            </foreignKey>
        </addForeignKeys>
    </changeSet>
</changeLog>

=== liquibase/liquibase4/liquibase-common/src/test/resources/liquibase/parser/expected/ParserFactoryTest.unparsed.addColumns.xml
<?xml version="1.1" encoding="utf-8"?>
<changeLog xmlns="http://www.liquibase.org/xml/ns/changelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/changelog http://www.liquibase.org/xml/ns/changelog/changelog-4.0.xsd">
    <changeSet author="test" id="1">
        <addColumns tableName="object_name" schemaName="schema_name" catalogName="cat_name">
            <checkConstraint disabled="true" name="abc" remarks="abc">abc</checkConstraint>
            <checkConstraint disabled="true" name="abc" remarks="abc">abc</checkConstraint>
            <column defaultValue="ANY OBJECT VALUE" name="abc" nullable="true" remarks="abc" type="INTEGER" virtual="true">
                <autoIncrementDetails incrementBy="4221" startWith="4221"/>
            </column>
            <column defaultValue="ANY OBJECT VALUE" name="abc" nullable="true" remarks="abc" type="INTEGER" virtual="true">
                <autoIncrementDetails incrementBy="4221" startWith="4221"/>
            </column>
            <foreignKey deferrable="true" deleteRule="cascade" initiallyDeferred="true" name="abc" remarks="abc" updateRule="cascade" referencedTableName="object_name" referencedTableSchemaName="schema_name" referencedTableCatalogName="cat_name">
                <constraint baseColumn="abc" referencedColumn="abc"/>
                <constraint baseColumn="abc" referencedColumn="abc"/>
            </foreignKey>
            <foreignKey deferrable="true" deleteRule="cascade" initiallyDeferred="true" name="abc" remarks="abc" updateRule="cascade" referencedTableName="object_name" referencedTableSchemaName="schema_name" referencedTableCatalogName="cat_name">
                <constraint baseColumn="abc" referencedColumn="abc"/>
                <constraint baseColumn="abc" referencedColumn="abc"/>
            </foreignKey>
            <primaryKey clustered="true" name="abc" remarks="abc" tablespace="abc">
                <column direction="ASC" name="abc"/>
                <column direction="ASC" name="abc"/>
            </primaryKey>
            <uniqueConstraint deferrable="true" disabled="true" initiallyDeferred="true" name="abc" remarks="abc" tablespace="abc" backingIndexName="object_name" backingIndexTableName="table_name" backingIndexSchemaName="schema_name" backingIndexCatalogName="cat_name">
                <column>abc</column>
                <column>abc</column>
            </uniqueConstraint>
            <uniqueConstraint deferrable="true" disabled="true" initiallyDeferred="true" name="abc" remarks="abc" tablespace="abc" backingIndexName="object_name" backingIndexTableName="table_name" backingIndexSchemaName="schema_name" backingIndexCatalogName="cat_name">
                <column>abc</column>
                <column>abc</column>
            </uniqueConstraint>
        </addColumns>
    </changeSet>
</changeLog>
